version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build the Project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    machine: 
      image: ubuntu-2204:current
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:6+qHFQDbqCYFzFzHfY7fpBaly2rEB83DUxswOGj6dkI"
      - run:
          name: Deploy to Server
          command: |
            ls -al ./build
            scp -r ./build/* $SERVER_USER@$SERVER_IP:$SERVER_DIR
            ssh $SERVER_USER@$SERVER_IP "sudo systemctl restart nginx"

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master